<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pagar_payment_checkout</name>
   <tag></tag>
   <elementGuidId>a8983c82-9b98-4ce8-9e63-392fab36828a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payNamebaz']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payNamebaz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5737f93-780f-41a3-bd81-62a4fe38a1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payNamebaz</value>
      <webElementGuid>7f514dee-2ca7-4694-baeb-df81a6108676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_button__RQIW7 false undefined</value>
      <webElementGuid>fd094e63-e466-41ed-814a-de5710b2c6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pagar</value>
      <webElementGuid>1955414d-9639-422d-b120-c284556aae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payNamebaz&quot;)</value>
      <webElementGuid>7322acf1-d07f-40c0-ae38-3614dce5af81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='payNamebaz']</value>
      <webElementGuid>16a9ea52-2c0e-4bdb-a4c7-9b16ff64e8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='App_partial__10XfR']/section/div[9]/section/section/section/nav/div[2]/div/main/section/div[2]/div/div/div</value>
      <webElementGuid>3394651a-8b9c-4177-aa3b-9c4efd1491c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiendas Elektra, Salinas y Rocha, Presta Prenda y Bodega de Remates.'])[1]/following::div[4]</value>
      <webElementGuid>b0c9b544-0832-4c07-9aa0-c1c7d80adc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paga en cualquier sucursal de Banco Azteca ubicadas en:'])[1]/following::div[5]</value>
      <webElementGuid>68bd46d3-80b0-4c37-9105-8c7427ace372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros'])[1]/preceding::div[2]</value>
      <webElementGuid>cccbcb8f-297b-46b6-89ad-ba8a361be7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pagar']/parent::*</value>
      <webElementGuid>7f274869-4f3b-4bb2-9b18-0b54824f609f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/div</value>
      <webElementGuid>04832b23-f7f4-4365-b4fb-359bbc51637c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'payNamebaz' and (text() = 'Pagar' or . = 'Pagar')]</value>
      <webElementGuid>5c09331a-fc4b-40e4-bd0e-d299bc12a707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
