<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_arrow_drop_down_receiverName</name>
   <tag></tag>
   <elementGuidId>362a240f-9b6d-4104-b922-7694198ca0c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverName-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverName-display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f81441a-d5e3-4ef2-8e11-19fd46db81a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverName-display</value>
      <webElementGuid>a7155047-f99b-42e0-9f7a-63ba1a894060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>receiverName</value>
      <webElementGuid>15d149ca-ac96-456f-841c-a58feb4169aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>error</name>
      <type>Main</type>
      <value>Este campo es obligatorio</value>
      <webElementGuid>5919ec9c-1475-4617-9f3b-b932c6411ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre de la persona que recibe</value>
      <webElementGuid>467ec67a-83bb-432e-baa7-9d6530ccf996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverName-display&quot;)</value>
      <webElementGuid>6af4d00c-e88f-4ba9-8c5d-40910f35f42f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverName-display']</value>
      <webElementGuid>0915be2e-b35e-4796-98b4-bf51d9976259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Shipping_body__2hhAf']/section/section/div[8]/div/input</value>
      <webElementGuid>43e011cd-e34f-46c7-b3f4-2e68701316db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>70debc67-50b8-4273-a2ba-b63ba71338bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverName-display' and @name = 'receiverName' and @placeholder = 'Nombre de la persona que recibe']</value>
      <webElementGuid>41c9f58e-de8d-44c5-b5ee-574d03f5f7e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
