<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reference</name>
   <tag></tag>
   <elementGuidId>0d264a5f-7f9d-4247-93e2-59fa068da85d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reference-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference-display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bde1567b-08f0-436c-aa48-d948612368ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference-display</value>
      <webElementGuid>3d43cfbf-270d-4691-987e-61ed010758a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>1ee9f72e-ce2d-41f8-af00-8dae7c9f0dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia *</value>
      <webElementGuid>344d5c3c-4220-427d-97d0-7e3a77c06f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference-display&quot;)</value>
      <webElementGuid>0284c229-067d-466e-87bc-1dd0c86d402d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference-display']</value>
      <webElementGuid>2de1a461-75e4-4fa4-9865-0f0464e93216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Shipping_body__2hhAf']/section/section/div[5]/div/input</value>
      <webElementGuid>410dcdcc-bb5c-4220-8633-05d36538866c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>aa45ea0f-1dc0-40a1-a7c3-9130cf3c6e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference-display' and @name = 'reference' and @placeholder = 'Referencia *']</value>
      <webElementGuid>ce78ab9c-ee3b-4c17-a7a7-20b92d39418d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
