<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_postalCode_checkout</name>
   <tag></tag>
   <elementGuidId>8ff70993-96b9-4941-b75e-0b554273a945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4166ae4b-6469-4bbf-8d70-f47ecbd55444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_zipInput__3An5g</value>
      <webElementGuid>28003a6f-51d9-4fd6-ac9b-a4b6c34b215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPostalCode</value>
      <webElementGuid>f1c0f9a4-3d5c-4b31-9859-4b08c6d554f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>38b9541d-95ad-425d-9b98-6c7ee2eea1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPostalCode&quot;)</value>
      <webElementGuid>9e905b6b-e52b-4358-acea-0aafe68e2bd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPostalCode']</value>
      <webElementGuid>4af08dbc-83ae-4ed1-a616-1efdd7288f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='App_partial__10XfR']/div/div[2]/div[2]/div/input</value>
      <webElementGuid>2c1ed439-0ef6-43a1-b20c-c9c333fe5290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9d45778e-ed82-41ec-ad4f-aaeaba39e42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newPostalCode']</value>
      <webElementGuid>784f66e4-5283-4cfe-a8c8-a1927d1f29f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
