<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__street</name>
   <tag></tag>
   <elementGuidId>c7e681a0-d589-45e3-91dd-7b5de4704550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street-display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9b3191d-9854-4a19-91c9-6581b01e0f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street-display</value>
      <webElementGuid>5380506e-b52e-476e-a7d9-f1bf24614bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>e2ed26c6-53c2-4e1f-ab6b-381732705ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Calle *</value>
      <webElementGuid>64fde423-14fc-4686-b72e-3c4e0abae657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street-display&quot;)</value>
      <webElementGuid>1233ab13-c232-4512-9270-6d9bb6087633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street-display']</value>
      <webElementGuid>7eb03c00-fa18-481d-9b7a-063d694d537b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Shipping_body__2hhAf']/section/section/div[3]/div/input</value>
      <webElementGuid>f93d6b91-ddea-4500-a3e2-aaeea7a2fbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8ce44a13-65b7-46ab-ab73-f64aab5486f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street-display' and @name = 'street' and @placeholder = 'Calle *']</value>
      <webElementGuid>d1bd1cd6-7ae9-4d08-8062-1361d3acd752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
