<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number</name>
   <tag></tag>
   <elementGuidId>10d81f53-f0ae-4b57-b68a-46fdfa7f8ada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number-display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a321d4d-ecd5-4197-966c-1c1d65fc37fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number-display</value>
      <webElementGuid>90551da1-b9b4-41e2-954f-13d6130e2847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dd3063e8-c6f4-41fa-a1c1-9ac27fff7028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. exterior *</value>
      <webElementGuid>6efefb77-d48f-4346-b942-2bb04661d22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number-display&quot;)</value>
      <webElementGuid>a19c4158-c9da-4a16-9a3f-3bc5d63e3a8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number-display']</value>
      <webElementGuid>2664d7d9-e0f1-40e9-9a66-63c94f7fd086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Shipping_body__2hhAf']/section/section/div[4]/div/input</value>
      <webElementGuid>03fa55c0-56b4-440f-bf2d-1e62fdd3e6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>aaeecf4d-f238-4104-854b-9874cfb6c048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number-display' and @name = 'number' and @placeholder = 'No. exterior *']</value>
      <webElementGuid>d1fe018a-8f32-4e84-92c9-cea36680e1ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
