<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectStoreRadioButton_shipping_checkout</name>
   <tag></tag>
   <elementGuidId>cc5756d8-4c0f-4fac-a89a-9bef53ef07e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g > g > g > g > g > circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>e2ca8f1f-d64d-44cf-8f02-f879dbc8094b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a54ab0d6-c9bc-4526-9955-e61a01e19d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2c9933ea-2c6c-4e95-a951-e38584a07d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e794a549-dc23-49c7-becd-858516797010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFF</value>
      <webElementGuid>50b47980-5acb-4e0a-9993-1a3cfff3c57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Locator_list__1qoaI&quot;)/div[@class=&quot;Store_element__rVVdB undefined undefined&quot;]/div[@class=&quot;Store_radio__2DMcI&quot;]/svg[1]/g[1]/g[1]/g[1]/g[1]/g[1]/circle[1]</value>
      <webElementGuid>b9535d36-df47-43da-8c4a-7b1caf591a4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
