<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecciona una opcinLos OyamelesEl Rosario</name>
   <tag></tag>
   <elementGuidId>89a7e64c-d9a1-4301-b5a6-09048307be47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#neighborhood</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='neighborhood']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3cd3a786-b5aa-4057-91c4-a5666fca2e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>neighborhood</value>
      <webElementGuid>fa41a438-4c36-4645-a9a9-3729913a2491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>neighborhood</value>
      <webElementGuid>52ec8e35-2fd5-4e6e-b151-4c4d0dd6fe17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecciona una opciónLos OyamelesEl Rosario</value>
      <webElementGuid>77430c0f-c0cc-49fc-8507-0243bacf6505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;neighborhood&quot;)</value>
      <webElementGuid>8fc80edd-a45e-440b-914e-3a1fbcaf0b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='neighborhood']</value>
      <webElementGuid>23b865fe-3543-43f8-b6e3-6eee1ebe3e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Shipping_body__2hhAf']/section/section/div[6]/div/select</value>
      <webElementGuid>70f2d6dd-2955-4dec-8478-0a2410c7db0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colonia *'])[1]/following::select[1]</value>
      <webElementGuid>f0e1922f-7309-4096-ad8e-cdf3b8dbc754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>9d9b98ab-9956-4884-9f92-10bd34ed68ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[1]/preceding::select[1]</value>
      <webElementGuid>d4d26d8c-5c00-4d2c-be85-6e2c93ab2f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuar con el pago'])[1]/preceding::select[1]</value>
      <webElementGuid>948e4a4e-9c62-4520-88b6-2f899a39ac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c2874791-9c33-458e-a33b-de8419141baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'neighborhood' and @name = 'neighborhood' and (text() = 'Selecciona una opciónLos OyamelesEl Rosario' or . = 'Selecciona una opciónLos OyamelesEl Rosario')]</value>
      <webElementGuid>b10abadd-fef5-4422-af57-50e85071b1f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
