<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ropa deportiva MujerHasta 50 de descuen_5a1fdd</name>
   <tag></tag>
   <elementGuidId>e8b89707-6c72-481d-8140-a8395fed0178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.a-promoOne__img-t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='bannerNo-1']/div/div/section/section/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ddd8f02c-9e42-4169-9a41-c5e0a359a7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-promoOne__img-t</value>
      <webElementGuid>71216618-951c-459b-bde8-e3e4eee66dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/home/perso/GB_261222/bcperso_040123depmuj.jpg</value>
      <webElementGuid>0f15f292-0564-4d94-a4be-6f7371686066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ropa Deportiva Mujer | Liverpool</value>
      <webElementGuid>94655679-362c-481f-b65a-fb8b181b605c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ropa Deportiva Mujer | Liverpool</value>
      <webElementGuid>2a717ad4-c70a-463f-bbc5-8eabacb4184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;min-vh-100&quot;]/div[2]/main[1]/div[1]/div[1]/div[@id=&quot;bannerNo-1&quot;]/section[@id=&quot;bannerNo-1&quot;]/div[@class=&quot;o-mainBanner&quot;]/div[@class=&quot;slideshow-main-container&quot;]/section[@class=&quot;bannerCentral-web&quot;]/section[@class=&quot;o-mainBanner-t&quot;]/div[1]/a[1]/picture[1]/img[@class=&quot;a-promoOne__img-t&quot;]</value>
      <webElementGuid>81552241-64a8-45a7-bd09-05aa6b3e7a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='bannerNo-1']/div/div/section/section/div/a/picture/img</value>
      <webElementGuid>00cfc33d-e7b4-4b4d-8a2d-67f22b869036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ropa Deportiva Mujer | Liverpool']</value>
      <webElementGuid>d1f01cc4-23ea-4525-922e-94e28c122dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>c8be6e49-6ddf-470c-8ef1-1645a8516db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/digital/home/perso/GB_261222/bcperso_040123depmuj.jpg' and @alt = 'Ropa Deportiva Mujer | Liverpool' and @title = 'Ropa Deportiva Mujer | Liverpool']</value>
      <webElementGuid>2cb8caee-585c-4441-88a7-a4940ae12d8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
