<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkCartEnabled_checkout</name>
   <tag></tag>
   <elementGuidId>fecbb5da-75d5-4dd1-9cfd-d453bb031dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='breadcrumb_Tab__2S-ws breadcrumb_true__2YWpY undefined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.breadcrumb_Tab__2S-ws.breadcrumb_true__2YWpY.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b4084bf-8c9f-4924-9b76-ef45edb93b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb_Tab__2S-ws breadcrumb_true__2YWpY undefined</value>
      <webElementGuid>04625e7a-6a17-43e9-a242-020ace4216fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Verifica tu carritocart-checkout</value>
      <webElementGuid>e9d14fc4-7831-4707-a02e-5c7c7ea40950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb_Breadcrumb__1MIZI&quot;)/div[@class=&quot;breadcrumb_Tab__2S-ws breadcrumb_true__2YWpY undefined&quot;]</value>
      <webElementGuid>7a8d7b25-8cf1-4730-96ed-f13901ab1ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='breadcrumb_Breadcrumb__1MIZI']/div</value>
      <webElementGuid>09c30df7-cc40-49a0-87a5-37c8abe83cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Llama para comprar'])[1]/following::div[1]</value>
      <webElementGuid>c33d9531-b7cc-404c-b132-ced59ddff2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa tu correo'])[1]/preceding::div[1]</value>
      <webElementGuid>9c33638d-263d-4df3-b471-049790f5d9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>aa678ce9-8631-472d-936b-48f43282bf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1Verifica tu carritocart-checkout' or . = '1Verifica tu carritocart-checkout')]</value>
      <webElementGuid>36707a27-dbda-413c-9c97-5af5dd0f462e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
