<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productImage_pdp</name>
   <tag></tag>
   <elementGuidId>e2035e96-fbe2-4b2e-b7c0-327506051448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@class='vtex-store-components-3-x-productImageTag vtex-store-components-3-x-productImageTag--main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.vtex-store-components-3-x-productImageTag.vtex-store-components-3-x-productImageTag--main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36f7245d-f3af-4b9d-bc3b-615aa53c2b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vtex-preload</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b60bdee-5e18-49a7-b0c4-76bd576b744b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-store-components-3-x-productImageTag vtex-store-components-3-x-productImageTag--main</value>
      <webElementGuid>8724b0b8-4062-4517-aa40-3e6be25a5c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/arquivos/ids/3558516-800-auto?v=637994930945800000&amp;width=800&amp;height=auto&amp;aspect=true</value>
      <webElementGuid>a668387b-c251-45e3-8ca4-02113b291844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/arquivos/ids/3558516-600-auto?v=637994930945800000&amp;width=600&amp;height=auto&amp;aspect=true 600w,https://elektra.vtexassets.com/arquivos/ids/3558516-800-auto?v=637994930945800000&amp;width=800&amp;height=auto&amp;aspect=true 800w,https://elektra.vtexassets.com/arquivos/ids/3558516-1200-auto?v=637994930945800000&amp;width=1200&amp;height=auto&amp;aspect=true 1200w</value>
      <webElementGuid>a1751564-adce-4c76-acd5-3985b24e20db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>31055271</value>
      <webElementGuid>3290574b-9c87-49f0-8147-e7b3b15c4504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>31055271</value>
      <webElementGuid>0f005ac6-e0ed-4455-82dd-4c3c507295a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>fcfe702b-ee8f-4db3-9eb2-509856020c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 64.1rem) 100vw, 50vw</value>
      <webElementGuid>65f14890-665f-4a8c-9f0b-6d8ae7e55742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>2d2c8acb-30f2-4452-95ba-b7032ba14741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-product&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[@class=&quot;vtex-product-context-provider&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[5]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[1]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--prod-pag-usa&quot;]/section[@class=&quot;vtex-store-components-3-x-container ph3 ph5-m ph2-xl mw9 center&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--prod-pag-usa items-stretch w-100&quot;]/div[@class=&quot;pr0 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexCol vtex-flex-layout-0-x-flexCol--prod-pag-usa  ml0 mr0 pl0 pr0      flex flex-column h-100 w-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexColChild vtex-flex-layout-0-x-flexColChild--prod-pag-usa pb0&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow&quot;]/div[@class=&quot;flex mt4 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent items-stretch w-100&quot;]/div[@class=&quot;pr7 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--newstack&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--newstack items-stretch w-100&quot;]/div[@class=&quot;pr7 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--stack&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--stack items-stretch w-100&quot;]/div[@class=&quot;pr7 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexCol vtex-flex-layout-0-x-flexCol--colImgProduct  ml0 mr0 pl0 pr0      flex flex-column h-100 w-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexColChild vtex-flex-layout-0-x-flexColChild--colImgProduct pb0&quot;]/div[@class=&quot;vtex-stack-layout-0-x-stackContainer vtex-stack-layout-0-x-stackContainer--product relative&quot;]/div[@class=&quot;vtex-stack-layout-0-x-stackItem vtex-stack-layout-0-x-stackItem--product vtex-stack-layout-0-x-stackItem--first vtex-stack-layout-0-x-stackItem--product--first&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent items-stretch w-100&quot;]/div[@class=&quot;pr0 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-store-components-3-x-productImagesContainer vtex-store-components-3-x-productImagesContainer--carousel vtex-store-components-3-x-content w-100&quot;]/div[@class=&quot;vtex-store-components-3-x-carouselContainer relative overflow-hidden w-100 flex-ns justify-end-ns&quot;]/div[@class=&quot;w-100 border-box vtex-store-components-3-x-carouselGaleryCursor ml-20-ns w-80-ns pl5-ns&quot;]/div[@class=&quot;swiper-container swiper-container-initialized swiper-container-horizontal vtex-store-components-3-x-productImagesGallerySwiperContainer&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide vtex-store-components-3-x-productImagesGallerySlide center-all swiper-slide-active&quot;]/div[@class=&quot;vtex-store-components-3-x-productImage&quot;]/div[@class=&quot;relative&quot;]/div[1]/img[@class=&quot;vtex-store-components-3-x-productImageTag vtex-store-components-3-x-productImageTag--main&quot;]</value>
      <webElementGuid>c56fe6d1-4708-456c-816c-46ce8a0fcbab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='31055271'])[2]</value>
      <webElementGuid>60ed637f-cb4f-413c-a996-0c7312a59708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>4a3a10be-6395-47a9-bd62-0567807ba8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://elektra.vtexassets.com/arquivos/ids/3558516-800-auto?v=637994930945800000&amp;width=800&amp;height=auto&amp;aspect=true' and @alt = '31055271' and @title = '31055271']</value>
      <webElementGuid>f92b379a-3249-40fb-82b5-4f2c35b98ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
