<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutPagesBreadCrumb_checkout</name>
   <tag></tag>
   <elementGuidId>3c512009-7b41-4ba0-910e-21e0fa005f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='breadcrumb_Breadcrumb__1MIZI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#breadcrumb_Breadcrumb__1MIZI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>acdb7c30-d807-4f97-8840-ab3413123f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>breadcrumb_Breadcrumb__1MIZI</value>
      <webElementGuid>e89c6179-0023-4b44-8425-ac816439d8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box</value>
      <webElementGuid>698f2f85-dda8-4da9-9708-20a3ae6028b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb_Breadcrumb__1MIZI&quot;)</value>
      <webElementGuid>518bc9de-1a79-42c5-9b76-a1e4a20d11e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='breadcrumb_Breadcrumb__1MIZI']</value>
      <webElementGuid>bf1ede63-1b21-4219-830f-b6ad7df25a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='breadcrumb_Container__kk3aO']/section</value>
      <webElementGuid>e6fb91f2-0f76-4596-85c7-fd1ebb3c2432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Llama para comprar'])[1]/following::section[2]</value>
      <webElementGuid>1a28ee28-0314-4ba9-8e30-bfee6e057da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section</value>
      <webElementGuid>fa2ee37a-8176-48e9-9e34-8a85495b421a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'breadcrumb_Breadcrumb__1MIZI' and (text() = '1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box' or . = '1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box')]</value>
      <webElementGuid>6282fa64-2e95-4a6e-a2b6-14473d6305f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
