<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyEmailDisabled_checkout</name>
   <tag></tag>
   <elementGuidId>51db15ee-b371-4cac-913e-3c5f53c663e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='breadcrumb_Tab__2S-ws breadcrumb_false__2fqWs undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>23b75770-84cf-46b4-abd0-5dfb3b313f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1674903871362</value>
      <webElementGuid>886e6985-f742-447d-af52-5b3604bef873</webElementGuid>
   </webElementProperties>
</WebElementEntity>
