<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continuar_minicart</name>
   <tag></tag>
   <elementGuidId>1b24da1b-8cf4-44e6-b1ef-898e0614b5f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='proceed-to-checkout']/div
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9faa4248-dda9-49e8-bf1a-373af0b5a0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-button__label flex items-center justify-center h-100 ph6 w-100 border-box </value>
      <webElementGuid>3d75a567-410d-4f3b-b86e-9f74db84fa16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir al checkout</value>
      <webElementGuid>6655aea2-78dc-4c75-9ba2-5d088a9c713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proceed-to-checkout&quot;)/div[@class=&quot;vtex-button__label flex items-center justify-center h-100 ph6 w-100 border-box&quot;]</value>
      <webElementGuid>800769e5-7424-4ec5-ade4-42dd34f44710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='proceed-to-checkout']/div</value>
      <webElementGuid>ef669df3-347e-4472-bfde-b06cb84cd791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasas y fletes calculados en el carrito'])[1]/following::div[6]</value>
      <webElementGuid>7f5ec523-4035-4793-aa88-a2a6661cbea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$38,999.00'])[2]/following::div[6]</value>
      <webElementGuid>45a7eaad-0f7e-47be-b66b-b06f31eeaf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✖'])[3]/preceding::div[3]</value>
      <webElementGuid>063cba26-4473-4525-a2eb-fbdf083f2784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='motos italika'])[1]/preceding::div[6]</value>
      <webElementGuid>67747c09-b185-4a31-912f-336512dfc4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ir al checkout']/parent::*</value>
      <webElementGuid>5bf0ca8b-0d32-4dcd-9b2b-5bf19fbb5d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button/div</value>
      <webElementGuid>474311c4-163f-451d-8a05-4c5e3a0538a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ir al checkout' or . = 'Ir al checkout')]</value>
      <webElementGuid>8cdc8fb4-2462-4211-944d-8f921be1f9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
