<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Iniciarsesin_elektra-hp</name>
   <tag></tag>
   <elementGuidId>e41a2222-e2cb-454b-b838-718d8c89b87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='icn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.elektra-elektra-components-0-x-chevron.vtex-render-runtime-8-x-lazyload.ls-is-cached.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>082d0a10-666e-4667-a36f-303bf21543ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icn</value>
      <webElementGuid>1090c55a-596b-48bd-b1e1-ab4eb54e4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload ls-is-cached lazyloaded</value>
      <webElementGuid>d7482528-9407-48c7-887e-e4864f951e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>75e3cf82-2c02-4ac1-acb7-ab8c7746542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7dd9b4c1-2f9a-467d-97e2-f79c9ce85000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg</value>
      <webElementGuid>db62353c-f544-42b1-930d-3d81550e0ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-home&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-wrapper vtex-sticky-layout-0-x-wrapper--sticky-header-1&quot;]/div[@class=&quot;vtex-sticky-layout-0-x-container vtex-sticky-layout-0-x-container--sticky-header-1 z-999 relative left-0 right-0&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--menu-link&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-center vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--menu-link items-stretch w-100&quot;]/div[@class=&quot;pr0     flex&quot;]/div[@class=&quot;elektra-elektra-components-0-x-containerUserPlaceholder&quot;]/div[@class=&quot;elektra-elektra-components-0-x-placeholderNoLogin&quot;]/img[@class=&quot;elektra-elektra-components-0-x-chevron vtex-render-runtime-8-x-lazyload ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>85b4703c-a418-4137-827a-a10e8490b233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icn']</value>
      <webElementGuid>f3a38faf-851d-458a-8e5c-fc9910d11709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img[2]</value>
      <webElementGuid>6c6ebd1f-ba36-4336-a95b-30d8af5273d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icn' and @src = 'https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/Envios_table_content_Chevrone-down.svg']</value>
      <webElementGuid>a6a99d04-9307-420b-beb0-709d117582e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
