<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp_outlook</name>
   <tag></tag>
   <elementGuidId>d0125939-9bac-41db-8e1f-19225de3b755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@style='background:#efefef; border:1px solid #efefef; color:#E51E20; text-align:center; font-size:42px; padding:20px']//strong)</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>75412f93-5460-434f-b623-4faad07406b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>559036</value>
      <webElementGuid>a92709f6-9a3f-4333-acc7-ed7dff4fefaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[2]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_7183&quot;]/div[1]/div[@class=&quot;R1UVb&quot;]/table[1]/tbody[1]/tr[4]/td[@class=&quot;x_no-padding-top-bottom-mobile&quot;]/table[@class=&quot;x_container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_container-padding&quot;]/table[@class=&quot;x_columns-container&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_force-col&quot;]/table[@class=&quot;x_col-3&quot;]/tbody[1]/tr[1]/td[1]/div[2]/strong[1]</value>
      <webElementGuid>74980b22-91f7-4df0-bb1f-679d4fcac9e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div[2]/table/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/div[2]/strong</value>
      <webElementGuid>f0c1c7aa-a15e-4970-a107-6571eabfe89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola, sjagtap'])[1]/following::strong[1]</value>
      <webElementGuid>45508545-b70f-4e52-8700-60c853abd052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este es un procedimiento 100% seguro.'])[1]/preceding::strong[1]</value>
      <webElementGuid>61255cc7-e7a2-4a27-af4d-1c9b08965715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::strong[2]</value>
      <webElementGuid>3c4f6d46-7075-43ce-b1b4-6122f07d8732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='559036']/parent::*</value>
      <webElementGuid>5584c4a3-89cc-44b7-8e24-5dade4923f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/strong</value>
      <webElementGuid>b98a18f2-c263-4f93-96ac-26c57a73a79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '559036' or . = '559036')]</value>
      <webElementGuid>c01a84d6-0d91-44f8-b737-188cbaef16e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
