<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blusas_l1Category</name>
   <tag></tag>
   <elementGuidId>003fc0c9-7718-459d-b81d-6b0c3408165b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.line > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Blusas')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ceb0b12a-5c82-4d3f-9c4f-e9d189600947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ropa/ropa-de-dama/blusas</value>
      <webElementGuid>38ec25f2-a26d-4c9b-8ecd-5e1936c07c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blusas</value>
      <webElementGuid>d3c8aeb3-49ee-40a5-8654-36a327be15f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuDep&quot;)/div[1]/div[@class=&quot;menuBackground&quot;]/div[@class=&quot;containerMenu&quot;]/nav[@class=&quot;menu&quot;]/div[@class=&quot;menuAnimationContainer&quot;]/div[@class=&quot;containerDiv&quot;]/div[2]/div[@class=&quot;familyContainerAnimation&quot;]/div[@class=&quot;familyContainer&quot;]/div[@class=&quot;families&quot;]/div[@class=&quot;family&quot;]/div[2]/div[@class=&quot;line&quot;]/a[1]</value>
      <webElementGuid>12240f88-b72b-43ca-9b0c-715fdfb8f483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuDep']/div/div/div/nav/div/div/div[2]/div/div/div[3]/div/div[2]/div/a</value>
      <webElementGuid>714cf4d6-367e-431b-82aa-8f207cf433a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blusas')]</value>
      <webElementGuid>91fd57d7-baf2-48dc-a659-0a2cf86be03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dama'])[1]/following::a[1]</value>
      <webElementGuid>589895db-a795-4259-bf3b-0c8969ef45eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/following::a[22]</value>
      <webElementGuid>d521ea14-06b3-4998-8559-e9a8d019b86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops y Playeras'])[1]/preceding::a[1]</value>
      <webElementGuid>33f54aa4-730c-49f3-93d1-79858874cb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/preceding::a[2]</value>
      <webElementGuid>19cf90e1-2fb1-4bdb-bb50-ce9ab2f8afc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blusas']/parent::*</value>
      <webElementGuid>8ec2f173-ee8c-43c7-b4b2-a4648db3c953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ropa/ropa-de-dama/blusas')]</value>
      <webElementGuid>04a4ff56-63a5-4814-9d97-266791a652e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>9928cda2-3fe5-4864-be79-e091bed31c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ropa/ropa-de-dama/blusas' and (text() = 'Blusas' or . = 'Blusas')]</value>
      <webElementGuid>dac379b0-4001-476b-aad5-87056cec3a94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
