<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchBar_hp</name>
   <tag></tag>
   <elementGuidId>f0add862-3c7b-4f2f-8d5d-55df25388e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downshift-0-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#downshift-0-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb2433a5-de28-42bb-928e-a558c11e0530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-styleguide-9-x-input ma0 border-box vtex-styleguide-9-x-hideDecorators vtex-styleguide-9-x-noAppearance br2  br-0 br--left  w-100 bn outline-0 bg-base c-on-base b--muted-2 t-body pl5 </value>
      <webElementGuid>945d6db5-51ab-4cb3-9362-7e11d15f82f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2901143d-1e52-4b8c-ad04-1bac363ca63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar en Elektra...</value>
      <webElementGuid>1b8d3dcd-1b52-4d65-82f5-b695eac2c7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818cc786-78fd-4269-9b3e-8640b5d6eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-0-input</value>
      <webElementGuid>9261b441-0d36-4fed-8b21-bea00da3cf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-0-input&quot;)</value>
      <webElementGuid>b5028fbe-ae4a-4192-b3f8-c76af15f553a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downshift-0-input']</value>
      <webElementGuid>0fae387b-b6cb-45f6-88ec-34178d008520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e177ef55-727d-4b09-994d-8c4dedde4c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Buscar en Elektra...' and @type = 'text' and @id = 'downshift-0-input']</value>
      <webElementGuid>c6caba9f-02fa-42bf-bae0-7278839a0237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
