<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Telefona</name>
   <tag></tag>
   <elementGuidId>af8e67b1-5981-4a26-a0a0-8a5692c1306e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='target']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.labelData > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cc618120-aa13-490c-b78d-92d64a8ab9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telefonía</value>
      <webElementGuid>997152f5-eca1-4964-8021-b54b34473d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuDep&quot;)/div[1]/div[@class=&quot;menuBackground&quot;]/div[@class=&quot;containerMenu&quot;]/nav[@class=&quot;menu&quot;]/div[@class=&quot;menuAnimationContainer&quot;]/div[@class=&quot;containerDiv&quot;]/div[@class=&quot;categoryContainer&quot;]/div[@class=&quot;categoryDiv&quot;]/div[@class=&quot;category&quot;]/a[@id=&quot;target&quot;]/div[@class=&quot;labelData&quot;]/p[1]</value>
      <webElementGuid>685be095-7520-49a8-a503-b45c74411117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='target']/div/p</value>
      <webElementGuid>e9e15683-aaa4-4f96-9cd9-9c2bc506d3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/following::p[1]</value>
      <webElementGuid>5317becc-fccf-4000-9a65-eb53aba9d5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicia sesión'])[1]/following::p[1]</value>
      <webElementGuid>b174a7f4-4687-425a-9c90-b704fccf67b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marcas'])[1]/preceding::p[23]</value>
      <webElementGuid>360df464-9265-4e8d-99bd-ba401643d1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung'])[1]/preceding::p[23]</value>
      <webElementGuid>6e9e922a-670c-4d44-b085-b39918c366db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Telefonía']/parent::*</value>
      <webElementGuid>f2516967-b244-4e36-9286-3e23c96c581a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/p</value>
      <webElementGuid>5c8aa2d5-a407-4fa1-a20c-925c5a23c40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Telefonía' or . = 'Telefonía')]</value>
      <webElementGuid>63094fd9-9d8d-43ec-af4b-2ed625ccddfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
