<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productSection_myOrders</name>
   <tag></tag>
   <elementGuidId>da3a8138-a31d-4503-ade5-c0c74a1046d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.elektra-myaccount-orders-elektra-0-x-containerStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='febrero'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28806d3c-dbd4-4f50-bf11-c2e1e7e4cdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elektra-myaccount-orders-elektra-0-x-containerStatus</value>
      <webElementGuid>2c263f92-8dc1-4268-b368-e583268337e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Huawei Watch Fit 2 NegroCancelado</value>
      <webElementGuid>89386f53-220c-4cdb-8472-a3ca4e3680b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-account&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[5]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[2]/div[@class=&quot;vtex-account helvetica flex justify-around elektra-my-account-0-x-bgTransparent&quot;]/div[@class=&quot;elektra-my-account-0-x-container&quot;]/div[1]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[3]/section[@class=&quot;vtex-account__page w-100 w-80-m&quot;]/main[@class=&quot;vtex-account__page-body vtex-account__edit-order-id w-100 pa4-s&quot;]/div[@class=&quot;center w-100 helvetica&quot;]/section[@class=&quot;ph0&quot;]/div[1]/div[@class=&quot;elektra-myaccount-orders-elektra-0-x-contentStatus&quot;]/div[@class=&quot;elektra-myaccount-orders-elektra-0-x-containerStatus&quot;]</value>
      <webElementGuid>706636cd-ec61-4dea-a38a-9252af8b5c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='enero'])[1]/following::div[4]</value>
      <webElementGuid>a57ce50d-1d67-4dd5-8b5c-2125d39041b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='enero'])[2]/preceding::div[6]</value>
      <webElementGuid>647be4bd-ba24-4f29-82f1-3e150fa83b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>24193e37-1d71-4b5d-b9fc-9dba28e64feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Huawei Watch Fit 2 NegroCancelado' or . = 'Huawei Watch Fit 2 NegroCancelado')]</value>
      <webElementGuid>18e9a8ad-3809-43c2-8529-874e333a0497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
