<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nombre, decreciente_vtex-product-summar_9f1841</name>
   <tag></tag>
   <elementGuidId>3724e865-3e7a-4b78-9450-a4575ae609fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gallery-layout-container']/div/section/a/article/div/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.vtex-product-summary-2-x-imageNormal.vtex-product-summary-2-x-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2b8532ef-7643-4a75-a69c-f528406289f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/arquivos/ids/3719060-500-auto?v=1760024347&amp;width=500&amp;height=auto&amp;aspect=true</value>
      <webElementGuid>c1e8748d-8fa9-49c3-8397-9581db0a138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c11aeb3e-b99d-4faf-bec3-8a2db6b563fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Blusa Moda Oggi Mujer Mezclilla 2212303 Azul Claro Slim</value>
      <webElementGuid>de0e8fb0-92c5-419f-a766-3c0ceeaf5ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-product-summary-2-x-imageNormal vtex-product-summary-2-x-image</value>
      <webElementGuid>bf26a6d4-1c17-4b03-9788-b53288432098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>7165ff2c-8423-42df-baf6-0bb04d8e99cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gallery-layout-container&quot;)/div[@class=&quot;vtex-search-result-3-x-galleryItem vtex-search-result-3-x-galleryItem--normal vtex-search-result-3-x-galleryItem--grid pa4&quot;]/section[@class=&quot;vtex-product-summary-2-x-container vtex-product-summary-2-x-container--customPricePlp vtex-product-summary-2-x-container--OutletProductsNotAvailable vtex-product-summary-2-x-containerNormal vtex-product-summary-2-x-containerNormal--customPricePlp vtex-product-summary-2-x-containerNormal--OutletProductsNotAvailable overflow-hidden br3 h-100 w-100 flex flex-column justify-between center tc&quot;]/a[@class=&quot;vtex-product-summary-2-x-clearLink vtex-product-summary-2-x-clearLink--customPricePlp vtex-product-summary-2-x-clearLink--OutletProductsNotAvailable h-100 flex flex-column&quot;]/article[@class=&quot;vtex-product-summary-2-x-element vtex-product-summary-2-x-element--customPricePlp vtex-product-summary-2-x-element--OutletProductsNotAvailable pointer pt3 pb4 flex flex-column h-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexCol vtex-flex-layout-0-x-flexCol--promotion-image-svg  ml0 mr0 pl0 pr0      flex flex-column h-100 w-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexColChild vtex-flex-layout-0-x-flexColChild--promotion-image-svg pb0&quot;]/div[@class=&quot;vtex-stack-layout-0-x-stackContainer relative&quot;]/div[@class=&quot;vtex-stack-layout-0-x-stackItem vtex-stack-layout-0-x-stackItem--first&quot;]/div[@class=&quot;vtex-product-summary-2-x-imageContainer vtex-product-summary-2-x-imageWrapper db w-100 center&quot;]/div[@class=&quot;dib relative vtex-product-summary-2-x-imageContainer vtex-product-summary-2-x-imageStackContainer vtex-product-summary-2-x-hoverEffect&quot;]/img[@class=&quot;vtex-product-summary-2-x-imageNormal vtex-product-summary-2-x-image&quot;]</value>
      <webElementGuid>21885b4a-0969-4101-b968-085b580bd0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gallery-layout-container']/div/section/a/article/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>8ab500eb-8cca-49f3-a0d1-271111d9b6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Blusa Moda Oggi Mujer Mezclilla 2212303 Azul Claro Slim']</value>
      <webElementGuid>3ac2de15-3a09-435a-9ba5-0f76a2169320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>780216f5-d028-4e4e-bb03-d82deccbde27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://elektra.vtexassets.com/arquivos/ids/3719060-500-auto?v=1760024347&amp;width=500&amp;height=auto&amp;aspect=true' and @alt = 'Blusa Moda Oggi Mujer Mezclilla 2212303 Azul Claro Slim']</value>
      <webElementGuid>9d80ff53-65be-40f2-8461-4244635ea85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
