<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CieBancomer_payment_checkout</name>
   <tag></tag>
   <elementGuidId>dca54deb-0c31-4100-b18f-fe5130e93092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='PaymentMethods_method__3PcCF undefined']//div[contains(text(),'efectivo')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd28cd94-4f92-438e-825e-5ed6021475cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentMethods_methodName__6QLy0</value>
      <webElementGuid>6552a03f-4049-4fd5-8da8-d445aa8ec012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En efectivo en Banco Azteca o Elektra</value>
      <webElementGuid>0912f574-5e64-46b9-9d61-989ab9461ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App_partial__10XfR&quot;)/section[1]/div[@class=&quot;PaymentStep_module__5bUSo    undefined&quot;]/section[@class=&quot;PaymentStep_body__3YtId&quot;]/section[1]/section[@class=&quot;PaymentMethods_content__2jwCJ&quot;]/nav[@class=&quot;PaymentMethods_nav__3rF9g&quot;]/div[2]/div[1]/div[@class=&quot;PaymentMethods_method__3PcCF undefined&quot;]/div[@class=&quot;PaymentMethods_methodName__6QLy0&quot;]</value>
      <webElementGuid>9f9d2782-6904-433c-a35c-454d690ef54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='App_partial__10XfR']/section/div[9]/section/section/section/nav/div[2]/div/div/div[2]</value>
      <webElementGuid>de533e54-574e-4f7f-8b72-b9dc2e845a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal'])[1]/following::div[6]</value>
      <webElementGuid>c74db8b2-dfb5-4443-ab10-6db1bb3f7e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con QR'])[1]/following::div[11]</value>
      <webElementGuid>60ff8caf-dc29-4134-9b0e-613ea7a23bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros'])[1]/preceding::div[3]</value>
      <webElementGuid>89b9133c-e585-4b0f-817b-7335442f5080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='En efectivo en Banco Azteca o Elektra']/parent::*</value>
      <webElementGuid>5d9c049c-8e55-48f1-be08-8f9579a76d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div/div/div[2]</value>
      <webElementGuid>ef859741-5b22-46b6-909f-05556d0f4d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'En efectivo en Banco Azteca o Elektra' or . = 'En efectivo en Banco Azteca o Elektra')]</value>
      <webElementGuid>ee998e05-8351-4867-ba3b-3b3d146f37af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
