<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Buscar_checkout</name>
   <tag></tag>
   <elementGuidId>2e747f03-9508-4d26-aebd-b55ed7701342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cart_zipButton__3r548</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='App_partial__10XfR']/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78ba3c0d-55a2-44dc-81ee-49dcff584f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_zipButton__3r548</value>
      <webElementGuid>797c4eef-afe5-4993-a1ed-facd0fe505a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>6f8a6f69-8b8a-4264-8294-bc1ad8a852c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App_partial__10XfR&quot;)/div[1]/div[@class=&quot;cart_zipContainerCP__1dU6c&quot;]/div[@class=&quot;cart_zipCapture__1frOI&quot;]/div[@class=&quot;cart_zipButton__3r548&quot;]</value>
      <webElementGuid>a12bc96c-da73-4c0c-9833-78ed7014a3e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='App_partial__10XfR']/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>220aae6b-8728-4d71-b31e-5664f35f7882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa un código postal válido'])[1]/following::div[1]</value>
      <webElementGuid>bfbb0100-68c0-47c5-b47c-331caf9d7bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código postal'])[1]/following::div[1]</value>
      <webElementGuid>265bf4bb-727e-4f54-ad4c-d6ec0f52c7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona la forma de entrega'])[1]/preceding::div[1]</value>
      <webElementGuid>1d7ada59-5e3f-41b0-8070-894ea35ae115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>a5590a28-6154-443b-b5a7-7d6b8f312149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>c5aafa71-23a2-457a-8387-741e8ac94f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>28a145e3-dd02-4eb7-a837-061b6221e115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
