<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectStoreRadioButton_shipping_checkout</name>
   <tag></tag>
   <elementGuidId>7e367ff5-1e48-4410-8682-9394aaaf5f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g > g > g > g > g > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='Store_element__rVVdB undefined undefined']//div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>3a63793d-117a-4fa8-9e5e-ea6b8ac21e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>d108ad5f-756e-4094-8f4f-ef3506ec6008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f8e83610-57b5-4375-b8a2-03a928b57b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1899bfa0-efba-40e1-b371-98dd804bbbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFF</value>
      <webElementGuid>683f2432-46a8-4f46-ab70-60817324c016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Locator_list__1qoaI&quot;)/div[@class=&quot;Store_element__rVVdB undefined undefined&quot;]/div[@class=&quot;Store_radio__2DMcI&quot;]/svg[1]/g[1]/g[1]/g[1]/g[1]/g[1]/circle[1]</value>
      <webElementGuid>d1305235-c3a8-4c0a-af5d-900970436d23</webElementGuid>
   </webElementProperties>
</WebElementEntity>
