<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Telefona_vtex-store-components-3-x-imag_98c234</name>
   <tag></tag>
   <elementGuidId>08b3d621-2f2d-4c86-a1f2-09cd5899bad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Conectividad_Telefonía_Samsung_Galaxy_A04_64GB_W04_Dpto_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.vtex-store-components-3-x-imageElement.vtex-store-components-3-x-imageElement--image-banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2a88d01-76ba-4d38-b79c-ca16d33a8061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/017b15cd-2176-49c8-b985-54396d45c245___49b3cbfded6a44790daa3154fbb125d9.webp</value>
      <webElementGuid>73d23b58-9320-4fe7-9eda-56506c45392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Conectividad_Telefonía_Samsung_Galaxy_A04_64GB_W04_Dpto_2</value>
      <webElementGuid>12c1a294-271d-4967-aa80-473584abd76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--image-banner</value>
      <webElementGuid>551e9cb4-df00-43e2-aa09-baee4686390b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>50386ec5-d60b-4746-b039-c8b97f03f579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-vtex-store-2-x-store-custom-category-telefonia&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[5]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[4]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--row-elektra vtex-flex-layout-0-x-flexRow--row-departament&quot;]/section[@class=&quot;vtex-store-components-3-x-container ph3 ph5-m ph2-xl mw9 center&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--row-elektra vtex-flex-layout-0-x-flexRowContent--row-departament items-stretch w-100&quot;]/div[@class=&quot;pr0 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--col-images-banner&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--col-images-banner items-stretch w-100&quot;]/div[@class=&quot;pr4 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/a[@class=&quot;vtex-store-components-3-x-imageElementLink vtex-store-components-3-x-imageElementLink--image-banner&quot;]/img[@class=&quot;vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--image-banner&quot;]</value>
      <webElementGuid>d38d4151-ee2e-4339-9ea4-d5618189ac3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Conectividad_Telefonía_Samsung_Galaxy_A04_64GB_W04_Dpto_2']</value>
      <webElementGuid>b7b8277c-fcd9-4701-aa82-64e822692a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>830bd22c-86fe-4bb0-af6f-0884fdff6469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/017b15cd-2176-49c8-b985-54396d45c245___49b3cbfded6a44790daa3154fbb125d9.webp' and @alt = 'Conectividad_Telefonía_Samsung_Galaxy_A04_64GB_W04_Dpto_2']</value>
      <webElementGuid>8a64b98f-15c1-438e-8ad2-feb5ae8ca584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
