<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutPagesBreadCrumb_checkout</name>
   <tag></tag>
   <elementGuidId>d4377be5-a744-4532-ada1-1b722a3fa980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='breadcrumb_Breadcrumb__1MIZI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#breadcrumb_Breadcrumb__1MIZI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>8acd1534-e46c-4646-ad7d-061a68a965e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>breadcrumb_Breadcrumb__1MIZI</value>
      <webElementGuid>1831c226-25ed-4971-a7ab-b673c4d645b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box</value>
      <webElementGuid>82965931-245f-49c0-a0fa-fbe1bfe74ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb_Breadcrumb__1MIZI&quot;)</value>
      <webElementGuid>2f930a61-085b-4ef4-9742-139d8832a4f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='breadcrumb_Breadcrumb__1MIZI']</value>
      <webElementGuid>b5bcb737-5b75-4775-ae95-d1ba57bdd9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='breadcrumb_Container__kk3aO']/section</value>
      <webElementGuid>c5cb1549-009f-473e-9934-64457e3564f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Llama para comprar'])[1]/following::section[2]</value>
      <webElementGuid>5f67acbb-32e9-4d1d-921d-7234488e7052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section</value>
      <webElementGuid>75a05007-8557-4fdc-b40a-a7cbaa67b392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'breadcrumb_Breadcrumb__1MIZI' and (text() = '1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box' or . = '1Verifica tu carritocart-checkout2Ingresa tu correoenvelope3Selecciona tu envío y pagofree-shipping4Pedido confirmadoopen-box')]</value>
      <webElementGuid>b0d55c0e-9d2e-4b5e-be55-8ddbe1d8934e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
