<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CieBancomer_payment_checkout</name>
   <tag></tag>
   <elementGuidId>b31be4f4-e54f-46dc-8109-690171a2553c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='En efectivo en Banco Azteca o Elektra']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75a408d4-22e2-419d-9091-3f6ea8089f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentMethods_methodName__6QLy0</value>
      <webElementGuid>a0798b48-4dd4-43fd-852c-e7eed8733d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>En efectivo en Banco Azteca o Elektra</value>
      <webElementGuid>5aff221e-ce4f-438a-9aaf-351eb91b4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App_partial__10XfR&quot;)/section[1]/div[@class=&quot;PaymentStep_module__5bUSo    undefined&quot;]/section[@class=&quot;PaymentStep_body__3YtId&quot;]/section[1]/section[@class=&quot;PaymentMethods_content__2jwCJ&quot;]/nav[@class=&quot;PaymentMethods_nav__3rF9g&quot;]/div[2]/div[1]/div[@class=&quot;PaymentMethods_method__3PcCF undefined&quot;]/div[@class=&quot;PaymentMethods_methodName__6QLy0&quot;]</value>
      <webElementGuid>35a28205-e760-4596-8028-377504806665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='App_partial__10XfR']/section/div[9]/section/section/section/nav/div[2]/div/div/div[2]</value>
      <webElementGuid>b7cefda9-9cbc-46a4-8ce6-c300164cda73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal'])[1]/following::div[6]</value>
      <webElementGuid>07e75f2e-c532-4a28-a4f7-d0f8cce071fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con QR'])[1]/following::div[11]</value>
      <webElementGuid>d2e5d6d6-4336-4929-86e8-624946c15654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros'])[1]/preceding::div[3]</value>
      <webElementGuid>a812ddb0-0f8e-4f11-8b30-5d88f4c692d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='En efectivo en Banco Azteca o Elektra']/parent::*</value>
      <webElementGuid>df2d4b75-ef52-46f4-9066-4c34455fbcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div/div/div[2]</value>
      <webElementGuid>de30ac94-054e-4f85-b72b-66156c91e690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'En efectivo en Banco Azteca o Elektra' or . = 'En efectivo en Banco Azteca o Elektra')]</value>
      <webElementGuid>8ed7f422-cd72-4671-be82-bf01e6cb9db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
