<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continuar_submit_Shipping_checkout</name>
   <tag></tag>
   <elementGuidId>27e9b683-7a2d-4d4a-96fb-d8f919ec40a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Locator_buttonBar__28qUZ']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Locator_finderConfirmButton__JRhop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a54d319-04db-4116-b60a-4ef39daea6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Locator_finderConfirmButton__JRhop</value>
      <webElementGuid>2a806fb2-b1de-4342-8eb3-4d9f6c056bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>ea9cc8c5-3ca8-472a-9eb1-facb73b238ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Locator_buttonBar__28qUZ&quot;)/div[@class=&quot;Locator_finderConfirmButton__JRhop&quot;]</value>
      <webElementGuid>f70a180c-c244-4abc-9d25-a8e0740e2c7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Locator_buttonBar__28qUZ']/div</value>
      <webElementGuid>88f60ee3-1ede-409a-bde6-1054cdb020ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[20]/following::div[2]</value>
      <webElementGuid>8db74f9d-b9d7-4619-89f9-588d598f5e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piezas disponibles'])[20]/following::div[4]</value>
      <webElementGuid>f295178a-d362-45ea-bbfe-553bc84de958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To navigate, press the arrow keys.'])[1]/preceding::div[59]</value>
      <webElementGuid>faadc556-b9a2-484f-b924-159d65deea79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::div[84]</value>
      <webElementGuid>cc3ef148-04de-4c8e-ab0b-c797131070c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>ff9dc0e4-1ae4-412f-83a9-696861d0951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>e2f4d082-d50e-49f0-8920-3e4bebe8dafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>6140ac54-fc01-4075-9cfa-15cc8782ff9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
