<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectStoreRadioButton_shipping_checkout</name>
   <tag></tag>
   <elementGuidId>cc5756d8-4c0f-4fac-a89a-9bef53ef07e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>g > g > g > g > g > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='Store_element__rVVdB undefined undefined']//div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>277b9b68-f7cb-451e-bf01-0ac43ff305f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>73dc5156-3cc3-4901-b8c6-cff772a48d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>4bd6064f-3479-4657-b235-a5e1b2950401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>52203ea6-ec47-42b9-8b3e-abcd3eeddf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFF</value>
      <webElementGuid>ef3ddea7-88fb-41b1-bb4d-df9021bcd2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Locator_list__1qoaI&quot;)/div[@class=&quot;Store_element__rVVdB undefined undefined&quot;]/div[@class=&quot;Store_radio__2DMcI&quot;]/svg[1]/g[1]/g[1]/g[1]/g[1]/g[1]/circle[1]</value>
      <webElementGuid>69a7915a-4ebe-4781-8eed-6066b4a01111</webElementGuid>
   </webElementProperties>
</WebElementEntity>
