<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cart__396cs4</name>
   <tag></tag>
   <elementGuidId>21dfe0e7-6b32-40e1-a94a-516907471213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._396cs4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a64a2a9-5164-47c4-80df-d18adcdd1091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>31dbce89-830e-473e-aea8-4d919529e9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_396cs4</value>
      <webElementGuid>682bc57f-542e-4181-94e6-d61b113f7f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Grocery</value>
      <webElementGuid>da4cb973-327e-4588-b3e4-45fec136bae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100</value>
      <webElementGuid>744bbc25-444c-4444-b48e-fdd6981658ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn _2tvxW&quot;]/div[@class=&quot;InyRMC _3Il5oO&quot;]/div[@class=&quot;_37M3Pb&quot;]/div[@class=&quot;eFQ30H&quot;]/a[1]/div[@class=&quot;_1mkliO&quot;]/div[@class=&quot;CXW8mj&quot;]/img[@class=&quot;_396cs4&quot;]</value>
      <webElementGuid>36d14e9a-0dfd-4b59-a033-4b9077b1df13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div/a/div/div/img</value>
      <webElementGuid>64f8bc0f-896b-4046-b74d-e6a447b9c4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Grocery']</value>
      <webElementGuid>01a8adec-d195-4f14-a82a-d7708e49cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>dac19049-4bda-4e80-adaf-e20a46c4d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Grocery' and @src = 'https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100']</value>
      <webElementGuid>d4f45614-273c-4833-bcc9-f3d8f730fa8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
