<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>creditoElektraImage_plp</name>
   <tag></tag>
   <elementGuidId>742a6fed-111c-4471-aeb6-2d45126cfb47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@class='ekt-img'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ekt-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>711579cd-0227-40f4-b08a-f34556eb2afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ekt-img</value>
      <webElementGuid>de8d7dbc-aeac-43bd-9432-cc025369980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/CreditoVitrina_image.svg</value>
      <webElementGuid>aaf0bc42-3bd9-4b33-b255-4c22597955fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gallery-layout-container&quot;)/div[@class=&quot;vtex-search-result-3-x-galleryItem vtex-search-result-3-x-galleryItem--normal vtex-search-result-3-x-galleryItem--grid pa4&quot;]/section[@class=&quot;vtex-product-summary-2-x-container vtex-product-summary-2-x-container--customPricePlp vtex-product-summary-2-x-container--OutletProductsNotAvailable vtex-product-summary-2-x-containerNormal vtex-product-summary-2-x-containerNormal--customPricePlp vtex-product-summary-2-x-containerNormal--OutletProductsNotAvailable overflow-hidden br3 h-100 w-100 flex flex-column justify-between center tc&quot;]/a[@class=&quot;vtex-product-summary-2-x-clearLink vtex-product-summary-2-x-clearLink--customPricePlp vtex-product-summary-2-x-clearLink--OutletProductsNotAvailable h-100 flex flex-column&quot;]/article[@class=&quot;vtex-product-summary-2-x-element vtex-product-summary-2-x-element--customPricePlp vtex-product-summary-2-x-element--OutletProductsNotAvailable pointer pt3 pb4 flex flex-column h-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexCol vtex-flex-layout-0-x-flexCol--product-description-container  ml0 mr0 pl0 pr0      flex flex-column h-100 w-100&quot;]/div[@class=&quot;vtex-flex-layout-0-x-flexColChild vtex-flex-layout-0-x-flexColChild--product-description-container pb0&quot;]/div[@class=&quot;flex flex-column items-start credito-vitrina-container&quot;]/img[@class=&quot;ekt-img&quot;]</value>
      <webElementGuid>a6064d3b-abe0-4daf-8181-8aa708b56343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gallery-layout-container']/div/section/a/article/div[2]/div[4]/div/img</value>
      <webElementGuid>17fb4b3b-1945-463c-aafd-f3b85a1dfdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/CreditoVitrina_image.svg')]</value>
      <webElementGuid>e03a9a84-1855-4a81-9caf-b562e0ee6f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>f5811e41-6222-4e49-8ffe-93aa02d8998c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dh3yyy4wyj8lf.cloudfront.net/ekt-storefront/img-sites/components-io/CreditoVitrina_image.svg']</value>
      <webElementGuid>8d88bf50-2b23-4fd4-be54-19178aea5903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
