<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Color_plp</name>
   <tag></tag>
   <elementGuidId>bb03883c-baeb-4212-a5ed-418439d7bc90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='vtex-search-result-3-x-filter__container bb b--muted-4 vtex-search-result-3-x-filter__container--color']//input[@class='vtex-checkbox__input h1 w1 absolute o-0 pointer'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#color-plateado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>254b0a8e-d2de-4282-b54b-1409cd50429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-checkbox__input h1 w1 absolute o-0 pointer</value>
      <webElementGuid>982a94de-72ec-4d35-b3f5-9cb439319cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color-plateado</value>
      <webElementGuid>1482a8bc-605a-4452-a52d-d30f10e70138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Plateado</value>
      <webElementGuid>1abe7eb0-61d8-459b-8001-ec6e5e30a02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bc73ffb7-6c3c-4421-afa9-3de4b464ed59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4bc5490-dc8e-4173-8864-b34f8418ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Plateado</value>
      <webElementGuid>c4d05a44-9a24-4226-b474-9084a7150b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color-plateado&quot;)</value>
      <webElementGuid>2e56e8d4-f6ad-425b-95d6-1a1e7ff3c791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='color-plateado']</value>
      <webElementGuid>bffcce17-a9ed-47a0-89f5-565bc0ba39b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>2bf3f4b2-a29e-435e-8c82-c71a55aac62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'color-plateado' and @name = 'Plateado' and @type = 'checkbox']</value>
      <webElementGuid>cd051153-2771-494e-855d-618e526a25dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
