<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppleBrandImg_clp</name>
   <tag></tag>
   <elementGuidId>11cc79f5-0303-45a1-8583-3e139875c195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='vtex-slider-layout-0-x-imageElementLink vtex-slider-layout-0-x-imageElementLink--principal-carousel vtex-store-components-3-x-imageElementLink vtex-store-components-3-x-imageElementLink--principal-carousel'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0b7b193-f806-4808-b97b-1e432783955e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>APPLE</value>
      <webElementGuid>e5d43e63-22ce-4b3e-a03f-3ad12958246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/37e3a049-0c4e-4709-8576-e939ab16926a___b443aa0536530825a05aa1fac481dc9b.webp</value>
      <webElementGuid>fe61b7b8-61bf-482d-bb8e-77e56796705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-slider-layout-0-x-imageElement vtex-slider-layout-0-x-imageElement--principal-carousel vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--principal-carousel</value>
      <webElementGuid>c53af863-0299-4462-a03a-da6f1c376212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>68421f83-88f3-4bbd-ad10-d762368b3877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-vtex-store-2-x-store-custom-category-telefonia&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[5]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[1]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--slider-principal&quot;]/section[@class=&quot;vtex-store-components-3-x-container ph3 ph5-m ph2-xl mw9 center&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--slider-principal items-stretch w-100&quot;]/div[@class=&quot;pr0 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/section[@class=&quot;w-100 flex items-center relative vtex-slider-layout-0-x-sliderLayoutContainer vtex-slider-layout-0-x-sliderLayoutContainer--principal-carousel&quot;]/div[@class=&quot;w-100 vtex-slider-layout-0-x-sliderTrackContainer vtex-slider-layout-0-x-sliderTrackContainer--principal-carousel overflow-hidden&quot;]/div[@class=&quot;vtex-slider-layout-0-x-sliderTrack vtex-slider-layout-0-x-sliderTrack--principal-carousel flex justify-around relative pa0 ma0&quot;]/div[@class=&quot;vtex-slider-layout-0-x-slide vtex-slider-layout-0-x-slide--principal-carousel vtex-slider-layout-0-x-slide--visible vtex-slider-layout-0-x-slide--principal-carousel--visible flex relative&quot;]/div[@class=&quot;vtex-slider-layout-0-x-slideChildrenContainer vtex-slider-layout-0-x-slideChildrenContainer--principal-carousel flex justify-center items-center w-100&quot;]/a[@class=&quot;vtex-slider-layout-0-x-imageElementLink vtex-slider-layout-0-x-imageElementLink--principal-carousel vtex-store-components-3-x-imageElementLink vtex-store-components-3-x-imageElementLink--principal-carousel&quot;]/div[1]/img[@class=&quot;vtex-slider-layout-0-x-imageElement vtex-slider-layout-0-x-imageElement--principal-carousel vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--principal-carousel&quot;]</value>
      <webElementGuid>daf108bc-40a3-4721-85bc-05bd88bb80fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='APPLE']</value>
      <webElementGuid>16f68563-e839-4951-8b72-31744c607a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a/div/img</value>
      <webElementGuid>bbee952a-6007-4291-981e-0945fa4b2e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'APPLE' and @src = 'https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/37e3a049-0c4e-4709-8576-e939ab16926a___b443aa0536530825a05aa1fac481dc9b.webp']</value>
      <webElementGuid>051336da-e8e3-48a4-8994-b0c36c4c8e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
