<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bannerImg_clp</name>
   <tag></tag>
   <elementGuidId>dc6700e2-3eb2-4140-b604-bb33456c996f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='vtex-store-components-3-x-imageElementLink vtex-store-components-3-x-imageElementLink--image-banner-big']//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.vtex-slider-layout-0-x-imageElement.vtex-slider-layout-0-x-imageElement--banner-full.vtex-store-components-3-x-imageElement.vtex-store-components-3-x-imageElement--banner-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a15183e5-cb5d-4947-98ff-623d6d348428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/ba474724-e490-4701-9f47-3480a728daba___18ed2bbc5808e3ea6112ace1c024affc.webp</value>
      <webElementGuid>e9f86a0c-1a12-4b50-96a6-d35422956784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pleca_Bancaria_Telefonía_W02_Dpto_4</value>
      <webElementGuid>2fd32c90-33a2-4b81-9a28-ea6863366730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vtex-slider-layout-0-x-imageElement vtex-slider-layout-0-x-imageElement--banner-full vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--banner-full</value>
      <webElementGuid>0e1e0e0e-86fb-4f80-bf08-e38db9de40a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>0fdd67c8-d979-499c-b2bc-290c1f11a65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-vtex-store-2-x-store-custom-category-telefonia&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[5]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[7]/div[@class=&quot;vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--row-elektra vtex-flex-layout-0-x-flexRow--banner-full&quot;]/section[@class=&quot;vtex-store-components-3-x-container ph3 ph5-m ph2-xl mw9 center&quot;]/div[@class=&quot;flex mt0 mb0 pt0 pb0    justify-start vtex-flex-layout-0-x-flexRowContent vtex-flex-layout-0-x-flexRowContent--row-elektra vtex-flex-layout-0-x-flexRowContent--banner-full items-stretch w-100&quot;]/div[@class=&quot;pr0 items-stretch vtex-flex-layout-0-x-stretchChildrenWidth   flex&quot;]/section[@class=&quot;w-100 flex items-center relative vtex-slider-layout-0-x-sliderLayoutContainer vtex-slider-layout-0-x-sliderLayoutContainer--banner-full&quot;]/div[@class=&quot;w-100 vtex-slider-layout-0-x-sliderTrackContainer vtex-slider-layout-0-x-sliderTrackContainer--banner-full overflow-hidden&quot;]/div[@class=&quot;vtex-slider-layout-0-x-sliderTrack vtex-slider-layout-0-x-sliderTrack--banner-full flex justify-around relative pa0 ma0&quot;]/div[@class=&quot;vtex-slider-layout-0-x-slide vtex-slider-layout-0-x-slide--banner-full vtex-slider-layout-0-x-slide--firstVisible vtex-slider-layout-0-x-slide--banner-full--firstVisible vtex-slider-layout-0-x-slide--visible vtex-slider-layout-0-x-slide--banner-full--visible flex relative&quot;]/div[@class=&quot;vtex-slider-layout-0-x-slideChildrenContainer vtex-slider-layout-0-x-slideChildrenContainer--banner-full flex justify-center items-center w-100&quot;]/a[@class=&quot;vtex-slider-layout-0-x-imageElementLink vtex-slider-layout-0-x-imageElementLink--banner-full vtex-store-components-3-x-imageElementLink vtex-store-components-3-x-imageElementLink--banner-full&quot;]/div[1]/img[@class=&quot;vtex-slider-layout-0-x-imageElement vtex-slider-layout-0-x-imageElement--banner-full vtex-store-components-3-x-imageElement vtex-store-components-3-x-imageElement--banner-full&quot;]</value>
      <webElementGuid>45a322c8-8322-4131-a745-475ca15efe17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pleca_Bancaria_Telefonía_W02_Dpto_4']</value>
      <webElementGuid>26c30afb-8563-4996-aef5-8422753d55ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/img</value>
      <webElementGuid>1b930f2b-30d4-4376-bec5-565e0ea749b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://elektra.vtexassets.com/assets/vtex.file-manager-graphql/images/ba474724-e490-4701-9f47-3480a728daba___18ed2bbc5808e3ea6112ace1c024affc.webp' and @alt = 'Pleca_Bancaria_Telefonía_W02_Dpto_4']</value>
      <webElementGuid>346416bd-6bdf-4b35-8007-9df4672ab744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
