<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsletter_clp</name>
   <tag></tag>
   <elementGuidId>3e90f488-ff5f-4a4d-80d9-ad0203d854e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='newsletter-custom-wrapper']//div[@class='newsletter-custom-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90982ec8-0740-42f5-b9b1-eeb4bf6238fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suscríbete al newsletterY recibe las mejores ofertas sólo para ti¡Regístrate!Por favor, ingrese un correo electrónico válido.Al registrarme, acepto que mis datos sean tratados para fines mercadotécnicos de acuerdo al Aviso de PrivacidadContáctanos55 7577 5547Ventas y servicio al cliente: Lunes a Domingo 9:00am a 9:00pmcontacto@elektra.mxSíguenosAyudaCentro de ayuda¿Cómo comprar?Envíos y devolucionesServiciosFacturación ElectrónicaDescarga App Banco AztecaRecibe dinero del extranjeroCrédito Banco AztecaAcerca de ElektraHot SaleElektra en los mediosBuscador de tiendasEl Mejor Fin está en ElektraDescarga nuestra App ElektraAviso de privacidadEjerce tus derechos ARCOTérminos y condiciones Términos de promocionesLas promociones de www.elektra.mx pueden diferir de las promociones publicadas en tienda. El formato de los precios puede verse afectado por las configuraciones y diferencia de navegadores Derechos reservados 2022 Grupo Elektra</value>
      <webElementGuid>262dc7cc-6104-477a-8ad5-3af2b263b99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-vtex-store-2-x-store-custom-category-telefonia&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[8]</value>
      <webElementGuid>1327b492-76e0-4a36-aa97-e34be847dfc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fijos'])[1]/following::div[7]</value>
      <webElementGuid>1a93204c-7dcf-4cac-b5f5-6274c83250b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teléfonos inalámbricos'])[1]/following::div[7]</value>
      <webElementGuid>eb739726-df89-43ac-b068-5dbe43402d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[8]</value>
      <webElementGuid>c0f6a0d5-ac5f-4762-b094-e7f79a3952a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Suscríbete al newsletterY recibe las mejores ofertas sólo para ti¡Regístrate!Por favor, ingrese un correo electrónico válido.Al registrarme, acepto que mis datos sean tratados para fines mercadotécnicos de acuerdo al Aviso de PrivacidadContáctanos55 7577 5547Ventas y servicio al cliente: Lunes a Domingo 9:00am a 9:00pmcontacto@elektra.mxSíguenosAyudaCentro de ayuda¿Cómo comprar?Envíos y devolucionesServiciosFacturación ElectrónicaDescarga App Banco AztecaRecibe dinero del extranjeroCrédito Banco AztecaAcerca de ElektraHot SaleElektra en los mediosBuscador de tiendasEl Mejor Fin está en ElektraDescarga nuestra App ElektraAviso de privacidadEjerce tus derechos ARCOTérminos y condiciones Términos de promocionesLas promociones de www.elektra.mx pueden diferir de las promociones publicadas en tienda. El formato de los precios puede verse afectado por las configuraciones y diferencia de navegadores Derechos reservados 2022 Grupo Elektra' or . = 'Suscríbete al newsletterY recibe las mejores ofertas sólo para ti¡Regístrate!Por favor, ingrese un correo electrónico válido.Al registrarme, acepto que mis datos sean tratados para fines mercadotécnicos de acuerdo al Aviso de PrivacidadContáctanos55 7577 5547Ventas y servicio al cliente: Lunes a Domingo 9:00am a 9:00pmcontacto@elektra.mxSíguenosAyudaCentro de ayuda¿Cómo comprar?Envíos y devolucionesServiciosFacturación ElectrónicaDescarga App Banco AztecaRecibe dinero del extranjeroCrédito Banco AztecaAcerca de ElektraHot SaleElektra en los mediosBuscador de tiendasEl Mejor Fin está en ElektraDescarga nuestra App ElektraAviso de privacidadEjerce tus derechos ARCOTérminos y condiciones Términos de promocionesLas promociones de www.elektra.mx pueden diferir de las promociones publicadas en tienda. El formato de los precios puede verse afectado por las configuraciones y diferencia de navegadores Derechos reservados 2022 Grupo Elektra')]</value>
      <webElementGuid>4cfc1a7f-b3a3-482d-b7a1-d8fcd8031d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
