<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productDetails_confirmationPage</name>
   <tag></tag>
   <elementGuidId>d8872345-fbb5-4b8a-9632-dbfca92af2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de pago:'])[1]/following::table[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.elektra-elektra-components-0-x-itemsTable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>c0095d66-7cfd-4be0-9f9f-acdc215f3974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elektra-elektra-components-0-x-itemsTable</value>
      <webElementGuid>ff80d290-8680-449c-b8a0-d2d2ec6adb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProductoPrecio unitarioCantidadTotalhuawei watch fit 2 negro Entrega en 1 días*$2,9991$2,999*Fechas estimadas de entrega, sujeto a aprobación de pagoSubtotal$2,999EnvíoGratisTotal$2,999Los precios incluyen IVA y están expresados en moneda nacional</value>
      <webElementGuid>3b19d4f1-8b0c-4391-82e2-5096a02eb217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-base&quot;]/div[@class=&quot;render-container render-route-store-orderplaced&quot;]/div[@class=&quot;render-provider&quot;]/div[@class=&quot;vtex-store__template bg-base&quot;]/div[@class=&quot;flex flex-column min-vh-100 w-100&quot;]/div[2]/div[@class=&quot;flex flex-grow-1 w-100 flex-column&quot;]/div[1]/div[@class=&quot;vtex-order-placed-2-x-orderPlacedWrapper pt9 sans-serif&quot;]/div[@class=&quot;vtex-order-placed-2-x-orderPlacedMainWrapper mv6 w-80-ns w-90 center&quot;]/ul[@class=&quot;vtex-order-placed-2-x-orderList list pa0 ma0&quot;]/li[@class=&quot;vtex-order-placed-2-x-orderListItem db bb b--muted-4 pb9 mb9&quot;]/div[@class=&quot;vtex-order-placed-2-x-orderWrapper&quot;]/div[@class=&quot;elektra-elektra-components-0-x-walmartOrderPlaced elektra-elektra-components-0-x-wrapper&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;flex flex-column w-80 elektra-elektra-components-0-x-section2&quot;]/div[@class=&quot;flex flex-column elektra-elektra-components-0-x-section elektra-elektra-components-0-x-sectionPaquete&quot;]/div[@class=&quot;flex flex-column&quot;]/div[@class=&quot;elektra-elektra-components-0-x-itemsTableWrapper&quot;]/table[@class=&quot;elektra-elektra-components-0-x-itemsTable&quot;]</value>
      <webElementGuid>a462a97a-46e9-44b3-9939-110a81655a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de pago:'])[1]/following::table[1]</value>
      <webElementGuid>6d80b21a-cc0b-4bed-841a-73f77b22d470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table</value>
      <webElementGuid>e788fcc5-e087-457c-b1af-c5e9141844e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[(text() = 'ProductoPrecio unitarioCantidadTotalhuawei watch fit 2 negro Entrega en 1 días*$2,9991$2,999*Fechas estimadas de entrega, sujeto a aprobación de pagoSubtotal$2,999EnvíoGratisTotal$2,999Los precios incluyen IVA y están expresados en moneda nacional' or . = 'ProductoPrecio unitarioCantidadTotalhuawei watch fit 2 negro Entrega en 1 días*$2,9991$2,999*Fechas estimadas de entrega, sujeto a aprobación de pagoSubtotal$2,999EnvíoGratisTotal$2,999Los precios incluyen IVA y están expresados en moneda nacional')]</value>
      <webElementGuid>aed4e0fb-dd56-44d0-b13d-41e7d2430c37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
